### ISSUE TITLE
Design error

### ISSUE THREAD

**Issue by osleland** [SSDL-SNU/SNUPI#1]
I am able to use the example .json files, but when I run my file I get the following error

!! Design error
!!Please check lattice-type (honeycomb or square)
!! Or, please not locate bp-deletion on crossovers

I'm not sure what this means because I know I picked the right lattice type, I don't know how to fix the latter.

**Comment by SSDL-SNU** [comment]
Please check the design file has the bp-deletion at the crossover or terminal end of strands.
If so, try to move the location of the bp-deletion to the next one.

![image](https://user-images.githubusercontent.com/61811152/104864369-19498f00-597c-11eb-9b5d-500f952aa6cb.png)

Nevertheless, if not working, please let me check the design file. (mudge1998@snu.ac.kr)

**Comment by osleland** [comment]
That fixed the issue. Thank you!
