### ISSUE TITLE
SNUPI on M1 chip

### ISSUE THREAD

**Issue by Alpacalaca** [SSDL-SNU/SNUPI#12]
I have been trying to install SNUPI on my MacBook with a M1 chip. However, all of the Matlab compilers that are compatible with the current SNUPI builds are built for the intel chip. Do you have any recommendations?

**Comment by SSDL-SNU** [comment]
Hi,
That means you cannot install the runtime version, R2022b (9.13)? Um, I tested SNUPI on MacBook Pro 14 (2023), and it worked (maybe M2 chip). I cannot help you if the computer is not compatible with the runtime. But, as a compatible runtime is released, I will update the version. I recommend using other computers now. Sorry for that...
Best,
Jae Young
