### ISSUE TITLE
Import Sequences

### ISSUE THREAD

**Issue by osleland** [SSDL-SNU/SNUPI#2]
I get the same error when I upload the exported sequence .csv from cadnano alongside my .json file. I tested and found that the .json file works fine, but once I upload the .csv file it won't run. Here are the two files I'm trying to run as well as the error I get

Error using get_CSV_SEQ (line 10)
Assertion failed

Error in load_NA_DNA (line 166)

Error in INITIATE (line 64)

Error in MAIN (line 66)

MATLAB:assertion:failed

[Test_square.csv.txt](https://github.com/SSDL-SNU/SNUPI/files/5851153/Test_square.csv.txt)

I cant load my .csv file here

**Comment by SSDL-SNU** [comment]
The sequence seems '????' in the file, 'Test_square.csv.txt'. It should be the combination of A, T, G, and C. Please try to re-save your csv file, or may I check your json file?
