### ISSUE TITLE
SNUPI on Linux?

### ISSUE THREAD

**Issue by ErikPoppleton** [SSDL-SNU/SNUPI#3]
I'm very excited by the rapid prototyping that SNUPI offers, however it seems like the program is Windows-only?  I am not super familiar with Matlab, so perhaps I'm misunderstanding something, but is there a way to run the GUI on Linux or the code without the GUI within Matlab?

**Comment by SSDL-SNU** [comment]
The current files would not run for the other OS. I am working on it for Linux or Mac. I will upload it when it is done. Thank you.
