### ISSUE TITLE
single-stranded loops

### ISSUE THREAD

**Issue by KohlerF** [SSDL-SNU/SNUPI#4]
I encountered an issue trying to predict the structure of a design having single-stranded loops, using the Mac command line version with default parameters without providing a sequence file. 

I ran tests using four variants of the 6-helix bundle provided in the EXAMPLES directory, which I modified to have: 1) a scaffold loop, 2) scaffold overhangs, 3) a staple loop, 4) staple overhangs:
![6hb_Sc-loop](https://user-images.githubusercontent.com/36700176/139246168-f0dfb152-6978-4076-ab06-4032d0239a7b.png)            ![6hb_Sc-overhang](https://user-images.githubusercontent.com/36700176/139246191-9b132b80-3039-4c9b-a4d4-b24c5208ae0b.png)             ![6hb_St-loop](https://user-images.githubusercontent.com/36700176/139246214-1df9b2d0-cc60-45c3-b1bb-9f4f7a4c0329.png)           ![6hb_St-overhang](https://user-images.githubusercontent.com/36700176/139246255-9e5aa817-b5cf-4ddc-a003-7d9b307ca838.png)

The two variants having single-stranded staple overhangs or scaffold overhangs (multi-scaffold design required) work. For the two loop variants, I receive warnings of the following kind:

<img width="358" alt="examplary_warning_message" src="https://user-images.githubusercontent.com/36700176/139245203-7e648135-f911-41fb-aa74-21a9e8c0aeea.png">

Please see complete logs and outputs in the attached zip file:
[Outputs.zip](https://github.com/SSDL-SNU/SNUPI/files/7433658/Outputs.zip)

I would highly appreciate if you could fix this issue.

**Comment by SSDL-SNU** [comment]
I will reply that after checking it. Thank you for your comments.

**Comment by SSDL-SNU** [comment]
The designs were analyzed well in other OS (win or linux).
I found some minor errors in the mac version and uploaded the modified file (SNUPI_v1_01_mac.zip).
Please test the designs, and let me know if the running error still occurs.
Also, thank your feedback.

**Comment by KohlerF** [comment]
The new version works. I tested it with multiple designs. Thank your for solving the issue.
