### ISSUE TITLE
Mac - SNUPI2 - gen_PDB error

### ISSUE THREAD

**Issue by elija-feigl** [SSDL-SNU/SNUPI#6]
Hi, love to see how active the development is :)
I started testing Snupi2 right away. However, all runs with PDB or oxDNA file generation now fail. (tested 4 structures that worked with snupi1)

Here is the error message, I can send all files for testing if needed.

Unable to perform assignment because the size of the left side is 303750-by-1 and the size of the right side is 303090-by-1.
Error in PDB_Generator (line 317)
Error in gen_PDB (line 162)
Error in MAIN (line 343)
MATLAB:subsassigndimmismatch

**Comment by SSDL-SNU** [comment]
Hi, thank you for the test running. I tried to generate output files using other simple designs, but I cannot reproduce your error. Could you send me one of the design files with errors for checking? (snupicontact@gmail.com, or mudge1998@snu.ac.kr)
Thank you.

**Comment by SSDL-SNU** [comment]
Hi, I updated the modified version (v2.01). I hope the issue was solved. Thank you again.
