### ISSUE TITLE
Mac - SNUPI2.1 - RMSF

### ISSUE THREAD

**Issue by elija-feigl** [SSDL-SNU/SNUPI#7]
using the Mac OS version of snupi 2.1. on big sur 11.4.
it seems like the rmsf values are not written to the occupancy field in the PDB file.
strain energy is correctly added to the b-factor field.

**Comment by SSDL-SNU** [comment]
Hi, thank you for your report.
The files were re-uploaded (v2.01) with the modification of the errors. 
The RMSF will be exported correctly.

Thank you, 
Jae Young Lee

**Comment by elija-feigl** [comment]
awesome, I can confirm it works now :)
