### ISSUE TITLE
SNUPI2.1 - Stacking

### ISSUE THREAD

**Issue by elija-feigl** [SSDL-SNU/SNUPI#9]
SNUPI prediction of blunt end stacking inside origami structures does not conform to our experimental observations.
Motives such as crossover stacks (illustration attached) open up instead of staying fairly compact (screenshots 1).
Staples broken at crossovers ("half crossover") also lead to distortion of the structures (screenshots 2).

High resolution cryo-EM data suggests that these regions remain stable and at most display a small lateral shift.
Would it be possible to include an "internal stacking basepair" step to the model to properly account for these motifs?
Or  is there an alternative option to handle these situations? (have I maybe missed a setting?)
We can share design files and experimental data if required. 

I have also noticed that these structures take significantly longer (2-3times) than structures of similar size.

"crossover stack":
<img width="157" alt="Screenshot 2022-01-26 at 17 15 49" src="https://user-images.githubusercontent.com/26200491/151202766-96e30cb9-c87c-4f67-9005-4073869dc34d.png">
1. open stack:                        2. distorted feature:
<img width="287" alt="Screenshot 2022-01-26 at 17 14 47" src="https://user-images.githubusercontent.com/26200491/151202772-cf30e4e3-2fb3-47f2-a89c-0cefb6061848.png">  <img width="210" alt="Screenshot 2022-01-26 at 17 14 41" src="https://user-images.githubusercontent.com/26200491/151202781-a1b065df-5f34-4373-9146-79504f9864e1.png">

using the Mac OS version of snupi 2.1. on big sur 11.4.

**Comment by SSDL-SNU** [comment]
Thank you for your detailed comment.

Currently, the stacking interaction was not considered yet. 
The crossover stacks are considered disconnected (no structural elements), so the remaining electrostatic repulsion could widen the distance. 
Alternatively, if stacking forces can be assumed enough to keep the configuration (small lateral deformation), connecting some base-pairs in the stacking sites could give a similar prediction.
Anyway, this is not the implementation of stacking interaction.
I'm also welcome if I can see the details.

Thank you
Jae Young Lee

**Comment by elija-feigl** [comment]
Are there any plans to include such motifs in a future release of SNUPI?

These motifs have proven to be a helpful in staple breaking and seem to increase the structure's compactness.
Consequently they are used in our designs quite regularly. Connecting basepairs in the stacking site would require the removal of one of these crossover, hence significantly altering the overall design. 

Attached you find the cadnano design file of the left structure. 
[Twist_Tower_native.json.zip](https://github.com/SSDL-SNU/SNUPI/files/8197272/Twist_Tower_native.json.zip)

This structure was published a year ago with sub 8Å CryoEM data and a pseudo atomic model in:
Kube, M., Kohler, F., Feigl, E. et al. Revealing the structures of megadalton-scale DNA complexes with nucleotide resolution. Nat Commun 11, 6229 (2020). https://doi.org/10.1038/s41467-020-20020-7


A zoom in in the experimental data of the particular motif can be found in the Supplementary Data:
Supplementary Figure 41: Crossover Stack - Twist Tower native


Best regards, 
elija

**Comment by SSDL-SNU** [comment]
Thank you for the design file. 
The development of the model for stacking interaction is another interest of us. Its modeling will be included in the future version when it is done. As you know, the experimental results including the interesting paper are crucial for developing a computational model.

Thank you,
Jae Young
